### ISSUE TITLE
Setup testing

### ISSUE THREAD

**Issue by petergroenning** [MLOps-Group/shroom-classifier#4]
Write unit test

- For train, predict and model (i guess...)
- Calculate coverage

**Comment by s183920** [comment]
to test models from wandb, we need a way of logging in (without sharing personal access token)

**Comment by s180820** [comment]
I have made a test that uses wandb log in with a secret repository token, so we can now do more wandb testing. Havent made logging as I didn't wanna log something in wandb everytime we push to git.
